Expose private services on the host with a dynamic port.
So we don't conflict with services already running on the host, but can
still access private services directly from the host if we need to.

For some reason, elasticsearch fails to run with exposed ports, so it is
commented out for now. See:

```
ERROR: for elasticsearch  Cannot create container for service elasticsearch: Invalid bind mount spec "f36c5c8bb52c5e6f2aa1e1a99426030f7dbcb818ee263c1afdc5144acaeda465:data:rw": Invalid volume destination path: 'data' mount path must be absolute.
ERROR: Encountered errors while bringing up the project.
```