Pin djangorestframework<3.7 for use with Django 1.8
When versions of djangorestframework after and
including 3.7 are used with Django 1.8 they
produce the error:

    AttributeError: 'module' object has no attribute 'JSONField'