Pin django-polymorphic version < 0.8 for compatibility with Fluent Contents
django-fluent-contents is not yet compatible with django-polymorphic
versions after 0.8 due to changed import requirements.

See https://django-polymorphic.readthedocs.io/en/latest/changelog.html#version-0-8-2015-12-28

Fixes error:

    from polymorphic import PolymorphicManager, PolymorphicQuerySet
    ImportError: cannot import name PolymorphicManager