Pin django-mptt to < 0.8.5 to avoid publishing errors
The latest version 0.8.5 of django-mptt is not compatible with our
pinned <0.8 version of django-polymorphic which is required to keep
compatibility with Fluent Contents.

django-mpttt==0.8.5 makes the Fluent page models incompatible with
`deepcopy()` operations – via the django-polymorphic manager – and
therefore causes errors in ICEKit's publishing system which relies on
deep copying of draft items to make published copies.

See for example https://travis-ci.com/ixc/django-icekit/jobs/46167673

Here is an example stacktrace you see with django-mptt==0.8.5 which does
not occurr with django-mptt==0.8.4:

======================================================================
ERROR: test_render (icekit.plugins.image.tests.ImageItem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ixc/django-icekit/icekit/plugins/image/tests.py", line 55, in test_render
    self.page_1.publish()
  File "/home/travis/build/ixc/django-icekit/icekit/publishing/utils.py", line 33, in decorated
    return method(self, *args, **kwargs)
  File "/home/travis/build/ixc/django-icekit/icekit/publishing/models.py", line 238, in publish
    publish_obj = deepcopy(self)
  File "/opt/python/2.7.9/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/python/2.7.9/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/python/2.7.9/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/python/2.7.9/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/python/2.7.9/lib/python2.7/copy.py", line 172, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
  File "/home/travis/build/ixc/django-icekit/.tox/django18-py27/lib/python2.7/site-packages/polymorphic/manager.py", line 51, in __getattr__
    return super(PolymorphicManager, self).__getattr__(self, name)
TypeError: __getattr__() takes exactly 2 arguments (3 given)