Upgrade Pillow to 4+ so we can use BytesIO for image conversions #204
Pillow versions prior to 4 had a bug where you could not save any
image that required compression (e.g. TIFF, PNG) when using a
`BytesIO` object to store the image data.

This would result in the error message:
    OSError: encoder error -9 when writing image file